version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      APP_DEBUG: 'true'
      PHP_IDE_CONFIG: "serverName=docker"
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/config/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - mysymf-net

  webserver:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/config/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - app
      - db
    networks:
      - mysymf-net

  db:
    image: mysql:5.7.24
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mysymf
      MYSQL_ROOT_PASSWORD: root
      SERVICE_NAME: mysql5
      SERVICE_TAGS: dev
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/config/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - mysymf-net

networks:
  mysymf-net:
    driver: bridge

volumes:
  dbdata:
    driver: local